server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: tele
    password: 123456
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


rootId: 0